### ISSUE TITLE
User Story <TITLE>

### ISSUE THREAD

**Issue by Adimserious** [Adimserious/my-first-user-story-template#2]
In order to **give my thoughts on the love running event** as a **user**, I can **take part in a poll by selecting and submitting an answer**
In order to **gather feedback from user** as an **administrator**, I can **publish a poll**

## Acceptance Criteria
**Acceptance criteria 1**: There should be at least one option for the user to choose from
**Acceptance Criteria 2**: The option should appear as drop down list
**Acceptance Criteria 3**: There should be an option to add votes
**Acceptance Criteria 4**: There should be records of previous poll

# Tasks
- [ ] Task 1: Update the view, the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter 
- [ ] Task 2: Create a new field in the model to track the username
- [ ] Task 3: Update the view, add new votes
- [ ] Task 4: Record and document previous poll

**Comment by Adimserious** [comment]
cllose
